import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './styles.css';
import './enhancements.css';
import './activity.css';
import './leetcode.css';
import './terrain.css';
import './terrain-orbit.css';
import './terrain-density.css';
import './layout-density.css';
import './terrain-height.css';
import './terrain-city.css';
import './terrain-webgl.css';
import './spacing.css';
import './activity-responsive.css';
import './theme.css';
import './personal-image.css';
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
